[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "langchain>=1.4.2",
    "langchain-core>=1.6.4",
    "langchain-google-genai>=4.4.0",
    "langchain-nvidia-ai-endpoints>=1.4.3",
    "langchain-openai>=1.6.5",
    "langgraph>=1.2.12",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
